### ISSUE TITLE
Entrevista

### ISSUE THREAD

**Issue by GibranVasquez** [SistemasTecTlaxiaco/actividad-2-entrevista-team-gbkn#1]
https://drive.google.com/file/d/1OU_669J6X20vpokfyZ_PkumW-QTAmN6B/view?usp=sharing

**Comment by HECTOR-KDM02** [comment]
20 puntos(Cumple con todos los requisistos respectivamente y sin faltas)

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
